language: c
compiler:
  - gcc
  - clang

before_install: ./.travis/prepare.sh

env:
  - OPTS="--disable-ssl"
  - TESTSUITE=1 KERNEL=1 OPTS="--with-linux=./linux-3.14.7"
  - KERNEL=1 DPDK=1 OPTS="--with-dpdk=./dpdk-1.7.0

script: ./.travis/build.sh $OPTS
